In [1]:
from IPython.core.display import HTML
HTML("""
<style>

div.cell { /* Tunes the space between cells */
margin-top:1em;
margin-bottom:1em;
}

div.text_cell_render h1 { /* Main titles bigger, centered */
font-size: 2.2em;
line-height:1.4em;
text-align:center;
}

div.text_cell_render h2 { /*  Parts names nearer from text */
margin-bottom: -0.4em;
}


div.text_cell_render { /* Customize text cells */
font-family: 'Times New Roman';
font-size:1.5em;
line-height:1.4em;
padding-left:3em;
padding-right:3em;
}
</style>
""")

# Упражнения

### NUMPY

<img src='../../../img/trainings1.jpg'/>

1) Импортировать `NumPy` под именем `np`

In [2]:
import numpy as np

2) Напечатать версию и конфигурацию 

In [3]:
print(np.version.version)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3) Создайте нулевой вектор размером 10

In [4]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4) Создать вектор размера 10, заполненный единицами

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

5) Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [6]:
x = np.zeros(10)
x[5] = 1
x

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

6) Создать вектор со значениями от 10 до 49

In [7]:
# np.array(range(10, 50))
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

7) Создать и потом развернуть вектор (так, чтобы первый элемент стал последним)

In [8]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

8) Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [9]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

9) Создать 3x3 единичную матрицу

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

10) Создать массив 3x3x3 со случайными значениями

In [11]:
np.random.random((3,3))

array([[0.5090424 , 0.56427228, 0.79438758],
       [0.55654637, 0.50770628, 0.01430228],
       [0.2914649 , 0.13165226, 0.11430366]])

11) Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [12]:
x = np.random.random((10,10))
print(x)
print(x.min(), x.max())

[[0.84054789 0.84417476 0.22693916 0.65527198 0.16746173 0.398584
  0.83004567 0.7185457  0.0868047  0.22679298]
 [0.74893548 0.69246828 0.87034272 0.56497007 0.21990927 0.96655499
  0.90767668 0.13176768 0.59138475 0.09684305]
 [0.82627129 0.58042614 0.80818833 0.87252273 0.06688384 0.30074986
  0.76208189 0.6824501  0.26545517 0.52386503]
 [0.52529865 0.13759073 0.27815358 0.89704212 0.75392194 0.19910337
  0.95003719 0.94115518 0.26083657 0.34168935]
 [0.63739902 0.89605686 0.56658247 0.50563124 0.92934299 0.87657353
  0.77759305 0.68260816 0.72941614 0.56445003]
 [0.93962579 0.03170105 0.78110814 0.65193895 0.14276127 0.138687
  0.80299957 0.39555073 0.63813102 0.90649712]
 [0.66125748 0.00494356 0.21767173 0.48021089 0.58634463 0.52807964
  0.25384444 0.17069994 0.09442549 0.48935919]
 [0.53598957 0.07686165 0.21306404 0.83932104 0.46471085 0.95675611
  0.36558472 0.5664202  0.49040723 0.1757063 ]
 [0.15953661 0.20441224 0.82197817 0.6326665  0.83192968 0.32234916
  0.85725372 0.0

12) Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [13]:
x = np.random.random(30)
print(x)
print(x.mean())

[0.00572449 0.80437012 0.07021276 0.09226714 0.89667421 0.64838393
 0.61571053 0.32655887 0.8809771  0.12601676 0.13753961 0.62940395
 0.14428064 0.73633989 0.85410222 0.82043069 0.8543472  0.59389408
 0.68078784 0.9962507  0.1211477  0.93247989 0.5212457  0.16567912
 0.38950232 0.82236761 0.60638445 0.26004414 0.86602771 0.69111186]
0.5430087741675627


13) Создать матрицу с 0 внутри, и 1 на границах

In [14]:
np.matrix([[1, 1 ,1], [1, 0, 1], [1, 1, 1]])

matrix([[1, 1, 1],
        [1, 0, 1],
        [1, 1, 1]])

14) Создать 8x8 матрицу и заполнить её в шахматном порядке, не используя функцию tile

In [15]:
np.fromfunction(lambda x,y:(x+y)%2, shape=(8,8))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

15) Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [16]:
np.tile([0, 1], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

16) Перемножить матрицы размеров 5x3 и 3x2

In [17]:
a = np.random.random((5,3))
b = np.random.random((3,2))
a.dot(b)

array([[0.37202524, 1.44989745],
       [0.3537332 , 1.40054799],
       [0.36158896, 1.34509194],
       [0.34716217, 1.27343886],
       [0.27041257, 1.01650189]])

17) Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [18]:
a = np.arange(0,10,0.1)
a[(a>=3)&(a<=8)] *= -1
a

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9, -3. , -3.1, -3.2,
       -3.3, -3.4, -3.5, -3.6, -3.7, -3.8, -3.9, -4. , -4.1, -4.2, -4.3,
       -4.4, -4.5, -4.6, -4.7, -4.8, -4.9, -5. , -5.1, -5.2, -5.3, -5.4,
       -5.5, -5.6, -5.7, -5.8, -5.9, -6. , -6.1, -6.2, -6.3, -6.4, -6.5,
       -6.6, -6.7, -6.8, -6.9, -7. , -7.1, -7.2, -7.3, -7.4, -7.5, -7.6,
       -7.7, -7.8, -7.9, -8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9])

18) Создать 5x5 матрицу со значениями в строках от 0 до 4

In [19]:
np.tile(range(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

19) Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [20]:
np.linspace(0,1,10+2)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

20) Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [21]:
def kek(x,y):
    r = np.sqrt(x**2 + y**2)
    a = np.arctan(y/x)
    return r, a

a = np.random.random((10,2))
print(a)
b = np.array([kek(*el) for el in a])
b

[[0.71183828 0.04004407]
 [0.5742237  0.42129154]
 [0.49646322 0.30315418]
 [0.35484529 0.67154818]
 [0.90850653 0.07684064]
 [0.19551962 0.45618832]
 [0.37657999 0.60699517]
 [0.86223328 0.6935235 ]
 [0.96752607 0.35294162]
 [0.02347876 0.47381543]]


array([[0.71296372, 0.05619522],
       [0.71219338, 0.63296868],
       [0.58170283, 0.54819734],
       [0.75953416, 1.08468859],
       [0.9117503 , 0.08437825],
       [0.49632218, 1.16588539],
       [0.71432179, 1.0155115 ],
       [1.10653562, 0.67737801],
       [1.02989052, 0.34978751],
       [0.47439679, 1.52128428]])

21) Заменить максимальный элемент на ноль

In [22]:
a = np.random.random((10,1))
# a[a == a.max()] = 0
amax = a.max()
a[a == amax] = 0
a

array([[0.        ],
       [0.51159302],
       [0.39372053],
       [0.76645457],
       [0.52625417],
       [0.45659083],
       [0.15173301],
       [0.69742197],
       [0.12897084],
       [0.75781472]])

22) Из двух массивов сделать матрицу Коши $C (C_{ij} = \frac{1}{x_i - y_j})$

In [23]:
a = np.random.random((5,5))
b = np.random.random((5,5))
print(f'{a}\n\n{b}')

c = 1/(a-b)
c

[[0.10856778 0.23520714 0.22276761 0.86291338 0.5560337 ]
 [0.9143027  0.32866582 0.57341125 0.54905329 0.28966661]
 [0.2012487  0.63346027 0.28681846 0.39055084 0.14481384]
 [0.78137691 0.8712468  0.09771856 0.07413558 0.25222543]
 [0.41865493 0.78714704 0.19079989 0.61796802 0.17917674]]

[[0.37696008 0.70893708 0.9325714  0.47889945 0.69801149]
 [0.04104253 0.23033915 0.60248278 0.73008427 0.38142139]
 [0.75471657 0.32596143 0.65472862 0.05590094 0.03989163]
 [0.44680913 0.95316966 0.70242846 0.3205009  0.65445053]
 [0.41988632 0.35608106 0.51116495 0.91636742 0.15736926]]


array([[  -3.72588942,   -2.11090733,   -1.40884003,    2.6040722 ,
          -7.04335521],
       [   1.1451341 ,   10.17018026,  -34.39791574,   -5.52391634,
         -10.89861538],
       [  -1.80678963,    3.25204479,   -2.71805492,    2.98819753,
           9.53087013],
       [   2.98893094,  -12.20660588,   -1.65368551,   -4.05901281,
          -2.48617005],
       [-812.0896861 ,    2.3198305 ,   -3.12143897,   -3.35121316,
          45.85582416]])

23) Преобразовать массив из float в int

In [24]:
a = np.arange(10, dtype=float)
# a = np.array(a, dtype=int)
a = a.astype('int')
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

24) Случайно расположить p элементов в 2D массив

In [25]:
# ?
a = np.arange(9).reshape((3,3))
print(a)
np.random.shuffle(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


25) Отнять среднее из каждой строки в матрице

In [26]:
a = np.arange(9).reshape((3,3))
# b = np.zeros((3,3))
print(a)
amean = a.mean(axis=1)
amean = amean.astype(a.dtype)
for i in range(len(amean)):
#     b[i] = a[i] - amean[i]
    a[i] -= amean[i]
# print(b)
a

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

26) Найти диагональные элементы произведения матриц

In [27]:
# ?
a = np.random.random((5,3))
b = np.random.random((3,2))
c = a.dot(b)
print(c)
c.diagonal()

[[1.82692917 0.42681062]
 [1.36578701 0.31199154]
 [1.42858619 0.32377972]
 [0.25720607 0.13406314]
 [1.0442933  0.50330031]]


array([1.82692917, 0.31199154])

27) Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [28]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[0,0,0, x] for x in a[1:]])
b = np.concatenate((a[0:1], b.flatten()))
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

### Разреженные матрицы

<img src='../../../img/trainings.png'/>

1) Соберите из предложенной таблички csr-матрицу.
Дана таблица посещений пользователями сайтов.
Строки - описание сессий в интернете для пользователей. Польозватели закодированы числами(1-2-3) в столбце target. Сайты закодированы числами от 1 до 11. Нам не важно, что это были за сайты, при этом 0 - это не сайт, а отсутствие данных, когда за сессию было посещено менее 10 сайтов. 
Задача - собрать матрицу с частотными описаниями предпочтений пользователей, в которой для каждого сайта указывалось бы, сколько раз пользователь на него вообще заходил за все свои сессии.

Насколько эффективнее sparse матрица будет при количестве разных сайтов 10000? При количестве пользователей 1000?

In [29]:
import pandas as pd
data = pd.read_csv('../../../data/train_data_3users.csv')
data.drop('session_id', axis=1, inplace=True)

In [30]:
import scipy.sparse
scipy.sparse.csr_matrix(data.values)

<5x11 sparse matrix of type '<class 'numpy.longlong'>'
	with 37 stored elements in Compressed Sparse Row format>

2) Создать 2 случайные матрицы размерами 10х10 с долей ненулевых элементов не более 10% и перемножить в их в csr и numpy формате. Сравнить время 

### PANDAS

<img src='../../../img/trainings2.jpg'/>

**В задании предлагается с помощью Pandas ответить на несколько вопросов по данным репозитория UCI [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) (качать данные не надо – они уже есть в репозитории).

Уникальные значения признаков (больше информации по ссылке выше):
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

In [31]:
import pandas as pd
# чтоб картинки рисовались в тетрадке
%matplotlib inline 
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['figure.figsize'] = (10, 8)

In [32]:
data = pd.read_csv('../../../data/adult.data.csv')
data.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

1) Сколько мужчин и женщин (признак *sex*) представлено в этом наборе данных?

2) Каков средний возраст (признак *age*) женщин?

3) Постройте гистограмму распределения (*bar plot*) образования людей (признак *education*).

4) Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год?

5) Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак *education - Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)

6) Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.

7) Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).

###  Графики

<img src='../../../img/trainings.JPG' width=50%>

## Загрузка и знакомство с данными

Для работы вам понадобятся данные из учебного конкурса на kaggle [«Прогноз популярности статьи на Хабре»](https://inclass.kaggle.com/c/howpop-habrahabr-favs-lognorm). Файл **`howpop_train.csv`** уже лежит в нашем репозитории в каталоге **`data`**.

In [33]:
df = pd.read_csv('../../../data/howpop_train.csv')

In [34]:
df.shape

(134137, 17)

In [35]:
df.head(3).T

0  \
url                             https://habrahabr.ru/post/18284/   
domain                                              habrahabr.ru   
post_id                                                    18284   
published                                    2008-01-01 18:19:00   
author                                                    @Tapac   
flow                                                     develop   
polling                                                    False   
content_len                                                 4305   
title             Новогодний подарок блоггерам — WordPress 2.3.2   
comments                                                       0   
favs                                                           0   
views                                                        236   
votes_plus                                                     0   
votes_minus                                                    0   
views_lognorm                                          -0.792687   
favs_lognorm                                            -1.34407   
comments_lognorm                                        -2.43687   

                                                                  1  \
url                                https://habrahabr.ru/post/18285/   
domain                                                 habrahabr.ru   
post_id                                                       18285   
published                                       2008-01-01 18:30:00   
author                                                   @DezmASter   
flow                                                         design   
polling                                                       False   
content_len                                                    7344   
title             Сумасшедшие яйца, или сервис для отслеживания ...   
comments                                                          1   
favs                                                              1   
views                                                           353   
votes_plus                                                        1   
votes_minus                                                       0   
views_lognorm                                             -0.485214   
favs_lognorm                                              -0.831946   
comments_lognorm                                           -1.87319   

                                                                  2  
url                                https://habrahabr.ru/post/18286/  
domain                                                 habrahabr.ru  
post_id                                                       18286  
published                                       2008-01-01 18:34:00  
author                                                   @DezmASter  
flow                                                         design  
polling                                                       False  
content_len                                                    8431  
title             Сумасшедшие яйца, или сервис для отслеживания ...  
comments                                                         47  
favs                                                             72  
views                                                          1200  
votes_plus                                                       45  
votes_minus                                                       5  
views_lognorm                                               0.44609  
favs_lognorm                                                1.79402  
comments_lognorm                                           0.574656

Избавимся сразу от переменных, названия которых заканчиваются на `_lognorm`. Выберем их с помощью `filter()` и удалим `drop`-ом:

In [36]:
df.drop(filter(lambda c: c.endswith('_lognorm'), df.columns), 
        axis = 1,       # axis = 1: столбцы 
        inplace = True) # избавляет от необходимости сохранять датасет

In [37]:
df.describe().T

count           mean           std      min       25%  \
post_id      134137.0  181307.054265  81766.350702  18284.0  115565.0   
content_len  134137.0    7516.929699   8724.771640      1.0    2179.0   
comments     134137.0      39.625994     62.398958      0.0       7.0   
favs         134137.0      71.999866    145.854135      0.0       8.0   
views        134137.0   16631.013084  31479.819691      3.0    2100.0   
votes_plus   133566.0      35.536888     42.461073      0.0      11.0   
votes_minus  133566.0       8.050035     11.398282      0.0       2.0   

                  50%       75%        max  
post_id      182666.0  257401.0   314088.0  
content_len    4949.0    9858.0   352471.0  
comments         19.0      48.0     2266.0  
favs             27.0      78.0     8718.0  
views          7600.0   18700.0  1730000.0  
votes_plus       22.0      45.0     1466.0  
votes_minus       5.0      10.0      445.0

In [38]:
df.describe(include = ['object', 'bool'] # бинарные и категориальные переменные
           ).T

count  unique                                          top    freq
url        134137  134137            https://habrahabr.ru/post/197184/       1
domain     134137       2                                 habrahabr.ru   97048
published  134137  130291                          2011-06-14 15:52:00      39
author      97657   22077                                      @alizar    5292
flow        97048       6                                      develop   53318
polling    134137       2                                        False  129412
title      134137  133628  Интересные события, произошедшие в выходные      56

In [39]:
# настройка внешнего вида графиков в seaborn
sns.set_style("dark")
sns.set_palette("RdBu")
sns.set_context("notebook", font_scale = 1.5, 
                rc = { "figure.figsize" : (15, 5), "axes.titlesize" : 18 })

Столбец **`published`** (время публикации) содержит строки. Чтобы мы могли работать с этими данными как с датой/временем публикации, приведём их к типу `datetime`:

In [40]:
print(df.published.dtype)
df['published'] = pd.to_datetime(df.published, yearfirst = True)
print(df.published.dtype)

object
datetime64[ns]


Создадим несколько столбцов на основе данных о времени публикации:

In [41]:
df['year'] = [d.year for d in df.published]
df['month'] = [d.month for d in df.published]

df['dayofweek'] = [d.isoweekday() for d in df.published]
df['hour'] = [d.hour for d in df.published]

-----
Теперь Ваша очередь. В каждом пункте предлагается построить картинку и с ее помощью ответить на вопрос. Конечно, можно попытаться ответить на все вопросы только с Pandas, без картинок, но мы будем смотреть на (красивые) визуализации.   

#### 1\. В каком месяце (и какого года) было больше всего публикаций?

* март 2016,
* март 2015,
* апрель 2015,
* апрель 2016.

#### 2\. Проанализируйте публикации в этом месяце (из вопроса 1)

Выберите один или несколько вариантов:

* На графике не заметны какие-либо выбросы или аномалии,
* Один или несколько дней сильно выделяются из общей картины,
* На хабре _всегда_ больше статей, чем на гиктаймсе,
* По субботам на гиктаймс и на хабрахабр публикуют примерно одинаковое число статей.

Подсказки: постройте график зависимости числа публикаций от дня; используйте параметр `hue`

#### 3\. Выберите верное утверждение

* Больше всего просмотров (в среднем) набирают статьи, опубликованные в 12 часов дня;
* У опубликованных в 10 утра постов больше всего комментариев  (в среднем);
* Больше всего просмотров  (в среднем) набирают статьи, опубликованные в 6 часов утра;
* Максимальное число комментариев на гиктаймсе набрала статья, опубликованная в 9 часов вечера;
* На хабре дневные статьи комментируют чаще  (в среднем), чем вечерние.

#### 4\. Кого из топ-20 авторов (по числу статей) чаще всего минусуют (в среднем)?

* @Mordatyj
* @Mithgol
* @alizar
* @ilya42

#### 5\. Сравните субботы и понедельники

Правда ли, что по субботам авторы пишут в основном днём, а по понедельникам — в основном вечером?